//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futurum.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public int game_id { get; set; }
        public string game_name { get; set; }
        public byte[] game_photo { get; set; }
        public string game_photopath { get; set; }
    }
}
