//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futurum.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public int orderproduct_id { get; set; }
        public Nullable<int> orderproduct_order { get; set; }
        public string orderproduct_product { get; set; }
        public int orderproduct_quantity { get; set; }
        public decimal orderproduct_totalmoney { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
