//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futurum.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int report_id { get; set; }
        public System.DateTime report_datetimeopening { get; set; }
        public Nullable<System.DateTime> report_datetimeclosure { get; set; }
        public string report_workingtime { get; set; }
        public string report_employee { get; set; }
        public Nullable<int> report_totalmoney { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
