//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futurum.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string user_id { get; set; }
        public decimal user_money { get; set; }
        public string user_name { get; set; }
        public string user_surname { get; set; }
        public string user_phone { get; set; }
        public Nullable<System.DateTime> user_birthday { get; set; }
    }
}
